services:
  emqx:
    container_name: ${nameproject}
    image: emqx:5.7.2
    restart: always
    ports:
      - ${emqxdashport}:18083
    volumes:
      - ./emqx-data:/opt/emqx/data
      - ./emqx-log:/opt/emqx/log
    environment:
      EMQX_DASHBOARD__DEFAULT_PASSWORD: superAdmin
      EMQX_NODE__NAME: foo_emqx@${nameproject}
      TZ: "America/Bogota"